all: bwtencode bwtsearch

bwtencode: bwtencode.cpp 
	g++ -std=c++11 -o bwtencode bwtencode.cpp

bwtsearch: bwtsearch.cpp 
	g++ -std=c++11 -o bwtsearch bwtsearch.cpp

clean: 
	$(RM) bwtencode bwtsearch
